import './globals.css'
import type { Metadata } from 'next'
import { Philosopher } from 'next/font/google'

const philosopher = Philosopher({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Alinaintana.id',
  description: 'Generated by create next app',
  icons: './favicon.ico'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={philosopher.className}>{children}</body>
    </html>
  )
}
